### ISSUE TITLE
2012 鏈結無效問題

### ISSUE THREAD

**Issue by Mikimoto** [MOPCON/MOPCON#1]
公關組反應：
2012 相關程式複製一份到 2012 folder, 但原始檔案請務必保留在根目錄, 防止 2012 過去的行銷連結都還是連到原始路徑.

大致上可以用 404 handler 接到一支在 /404_rdr.php, 404_rdr.php 拿 PHP_SELF 檢查 is_file(2012/{$PHP_SELF}.php), TRUE 就轉過去, 不然就丟到標準 404 頁面

**Comment by cdchen** [comment]
Dears,

  可否請教是哪些「行銷連結」出了問題呢??

Mikimoto notifications@github.com 於 2013/5/11 下午6:36 寫道：

> 公關組反應：
> 2012 相關程式複製一份到 2012 folder, 但原始檔案請務必保留在根目錄, 防止 2012 過去的行銷連結都還是連到原始路徑.
> 
> 大致上可以用 404 handler 接到一支在 /404_rdr.php, 404_rdr.php 拿 PHP_SELF 檢查 is_file(2012/{$PHP_SELF}.php), TRUE 就轉過去, 不然就丟到標準 404 頁面
> 
> —
> Reply to this email directly or view it on GitHub.

## 

陳 永昇 (Cd Chen)
http://www.cdchen.idv.tw/
mailto:cdchen@cdchen.idv.tw
mailto:cdchen.tw@gmail.com
mailto:cdchen@me.com
msn:cdchen@cdchen.idv.tw
icq:3345768

**Comment by Mikimoto** [comment]
聽說幾乎全部的頁面有有鏈結在外

**Comment by cdchen** [comment]
Dears,

  您的意思是，外面的網站上，有咱們網頁的連結嗎??

  如果是這樣，就傷腦筋了~~

Mikimoto notifications@github.com 於 2013/5/14 下午8:48 寫道：

> 聽說幾乎全部的頁面有有鏈結在外
> 
> —
> Reply to this email directly or view it on GitHub.

## 

陳 永昇 (Cd Chen)
http://www.cdchen.idv.tw/
mailto:cdchen@cdchen.idv.tw
mailto:cdchen.tw@gmail.com
mailto:cdchen@me.com
msn:cdchen@cdchen.idv.tw
icq:3345768

**Comment by Mikimoto** [comment]
我處理完了 :p
