### ISSUE TITLE
<許願> 每個議程獨立頁面

### ISSUE THREAD

**Issue by ericpi** [MOPCON/MOPCON#101]
今年可以每個議程獨立頁面嗎?

1) 裡面包含完整議程/講者 og 資訊, 這樣行銷上在 SNS比較好廣告
2) 底下可以接 disqus 或 FB social plug-in, 比較方便非 geek 參與者表達意見

**Comment by chusiang** [comment]
目前有打算用 markdown 來寫議程相關資訊，到時網站說不定可以直接 markdown?

**Comment by hashman** [comment]
太久了就關掉囉
