### ISSUE TITLE
2015 VIP 報名用圖

### ISSUE THREAD

**Issue by Mikimoto** [MOPCON/MOPCON#102]
![desktop](https://cloud.githubusercontent.com/assets/143029/9805729/19f9840a-586f-11e5-9670-cbd883fbd3be.png)

**Comment by chusiang** [comment]
上圖的講者分別為：
1. Blue, Anistar Carl, Akane
2. Joe, Kny, Ben, Jeremy, Muki
3. SJ, TK, 張逸中, Sam

**Comment by hashman** [comment]
太久了就關掉囉
