### ISSUE TITLE
將 2017 資料改為靜態

### ISSUE THREAD

**Issue by hashman** [MOPCON/MOPCON#105]
避免 Google Spreadsheets 改動到而影響 2017 的資料

**Comment by hashman** [comment]
這個請 @duley666 有空幫忙檢查一下是否都完成了，謝謝

**Comment by xwang0929** [comment]
@hashman 
有3支檔案還會向 google spreadsheet 要資料：

2017/javascript/vendor.js
2017/src/index.php
2017/live.php

需要我改嗎？

**Comment by hashman** [comment]
@duley666 
* 2017/live.php 可以砍掉了
* 2017/src/index.php 這個麻煩你調整了，但可以確認一下這個 function 還有沒有使用到，看起來應該是有機會拔除的

```
index.php
17:    'stream' => getStream(),

live.php
9:    'stream' => getStream(),

src/index.php
13:function getStream()
```

* 2017/javascript/vendor.js ? 這個好像是 js 的 asset 應該沒有使用到？

**Comment by xwang0929** [comment]
@hashman 請參照 pr #140 

- live.php 砍了。
- getStream() 只有首頁跟直播頁有用到，目前只有換掉 api。如果"拔除"是指拿掉所有相關的程式，我再另外處理。
- vendor.js 裡的 getSpreadsheetData 只有在 badge.twig 用到，應該是2017年大地遊戲時用的，一樣換掉 api。
