### ISSUE TITLE
Community 新增欄位, 異動欄位

### ISSUE THREAD

**Issue by Jackson45252** [MOPCON/MOPCON#109]
Community 新增

- id 

異動

-  name 跟 name_info 改為 info & info_en
-  原本的 info 改為 fb_link & other_link ( googlesheet 有在加其他連結了)

**Comment by Jackson45252** [comment]
已完成新增、異動

**Comment by bbandydd** [comment]
欄位缺少logo

**Comment by Jackson45252** [comment]
已新增
