### ISSUE TITLE
題庫&攤位任務日期欄位調整成在一起

### ISSUE THREAD

**Issue by Jackson45252** [MOPCON/MOPCON#116]
> [
>     {
>         "date": "2018-01-01",
>         "items": [
>             {
>                 "id": "001",
>                 "type": "quiz",
>                 "title": "什麼是區塊鏈",
>                 "description": null,

date 部分不用區分，兩天都放在一起就好

**Comment by uWayLu** [comment]
不用 date, 直接都塞在 items 裡面嗎?

**Comment by hashman** [comment]
舊的 feature 就關掉了，新的 feature 今年再說
