### ISSUE TITLE
答題&任務獎勵欄位

### ISSUE THREAD

**Issue by Jackson45252** [MOPCON/MOPCON#117]
jacksonxu [11:00 AM]
那就是再做一個對應的獎勵列表麻??

Don [11:00 AM]
其實任務列表就可以存對應獎勵的資料了
實作面還是看你們方便
是感覺不用特別用一個表來記錄

可以在任務列表裡面同時存「答題」和「攤位」的任務，包括獎勵的欄位。
如果獎勵多少不適合丟出來給客戶端，就不顯示這個欄位就可以了～

jacksonxu [11:01 AM]
那就是還要加個欄位嚕?

Don [11:02 AM]
也可以不加，需要知道獎勵多少的地方看設計圖只有「答題成功」的時候呢
不加是指客戶端不一定需要知道喔～
我這邊只有列客戶端需要的東西
所以實作的部分你要問後端 看他是想要放在一起還是分一張表

**Comment by hashman** [comment]
舊的 feature 就不留了，新的 feature 今年再說了
