### ISSUE TITLE
社群頁面 CHK logo size 需要最佳化一下

### ISSUE THREAD

**Issue by Mikimoto** [MOPCON/MOPCON#13]

**Comment by weitsai** [comment]
我應該要去哪裡取得 logo 呢?

還是直接把 git 上的檔案下載下來然後進行尺寸修改

**Comment by ericpi** [comment]
用 git 上檔案調整即可, 現在是圖片尺寸太大

**Comment by cdchen** [comment]
webbert，要不要領這個 issue??

**Comment by weitsai** [comment]
目前我將圖片改為 240 x 240，副檔名為 png，請問是這個問題嘛？

**Comment by weitsai** [comment]
@Mikimoto https://github.com/MOPCON/MOPCON/commit/979c66c2ed3463a966e78db353cb85c3b82a4874

**Comment by cdchen** [comment]
@webbertsai  2013 年的部份，也麻煩您了，謝謝!!

**Comment by cdchen** [comment]
@webbertsai  辛苦啦，感謝您的付出，謝謝!!
