### ISSUE TITLE
移除 Google plus 相關 icon

### ISSUE THREAD

**Issue by hashman** [MOPCON/MOPCON#134]
4/2 就要移除這個產品：https://technews.tw/2019/02/01/good-bye-google-plus/

就將相關的 icon 都移除吧

**Comment by hashman** [comment]
這個給 @hsimao 試試看吧，有問題都可以提出，謝謝

**Comment by ghost** [comment]
> 這個給 @hsimao 試試看吧，有問題都可以提出，謝謝

hash組長～求救，我try了很久MOPCON專案還是運行不起來～我確定 composer 跟 laravel 都有安裝哩
我的步驟如下～不知是否哪裡做錯哩...

1.) 安裝 npm 相依插件: npm install
2.) 更新 composer: composer install
3.) 運行 laravel 環境: php artisan serve

之後就報錯了，說找不到 artisan ..

**Comment by hashman** [comment]
他只是純的 PHP 專案，他不是 Laravel 專案唷，僅需要 1.2 即可，另外是你需要安裝 apache 軟體，把你的 php 專案 run 起來

**Comment by ghost** [comment]
> 他只是純的 PHP 專案，他不是 Laravel 專案唷，僅需要 1.2 即可，另外是你需要安裝 apache 軟體，把你的 php 專案 run 起來

原來如此～～謝謝組長 好的我在來試試😂

**Comment by hashman** [comment]
apache 軟體的話，如果是 Mac 可以安裝 MAMP 可以省不少功夫

**Comment by ghost** [comment]
> apache 軟體的話，如果是 Mac 可以安裝 MAMP 可以省不少功夫

成功哩～～我剛好也是用MAMP成功運行哩～～
