### ISSUE TITLE
將 2018 的資料改為靜態

### ISSUE THREAD

**Issue by hashman** [MOPCON/MOPCON#135]
MOPCON 2018 官網內容是採用 Google Sheet 的表單作為資料來源轉換成 json 供網站作為資料來源使用
為了維持網站穩定性，希望將這個抓取線上 json 的行為轉換為 local file 進行讀取
麻煩協助將以下頁面更改為讀取靜態 json 使用

- [x] 議程頁面
- [x] 講者頁面
- [x] 贊助商頁面
- [x] 主辦社群
- [x] 志工
- [x] 最新消息

**Comment by hashman** [comment]
上面都完成了，可以幫忙評估 `api/src/app/Models/MopConResource.php` 這個是否可以移除？

**Comment by hashman** [comment]
這個請 @Zames-Chang 幫我確認是否都完成了，謝謝

**Comment by Zames-Chang** [comment]
@hashman  評估過了，可以移除掉沒有問題，以下為評估方法
1 確認程式碼中有無使用 MopConResource
    僅 ApiController 有引入，但沒有實際使用他。
2 確認移除後網頁是否有問題
    沒有，跟原本長得一樣。

**Comment by hashman** [comment]
@Zames-Chang ok 再開一個 PR 處理掉它，謝謝

**Comment by hashman** [comment]
麻煩 @Zames-Chang 請至 https://dev.mopcon.org 進行確認，是否有問題，謝謝

**Comment by Zames-Chang** [comment]
> 麻煩 @Zames-Chang 請至 https://dev.mopcon.org 進行確認，是否有問題，謝謝

done 沒有問題

**Comment by hashman** [comment]
Release 出去了
