### ISSUE TITLE
移除不必要的檔案

### ISSUE THREAD

**Issue by hashman** [MOPCON/MOPCON#136]
先整理一些應該不會使用到的東西，或是有用到就之後再重弄就好

## 後端
- [ ] .tmp/vendor
- [ ] 2014_test
- [ ] 2015_preview_1

## 前端
- [ ] bower.json
- [ ] google8bcd5019745af818.html

**Comment by hashman** [comment]
前端給 @Tzuhui 後端給 @FWcloud916 試試看

**Comment by Tzuhui** [comment]
@hashman 有兩個問題想請問～
1. google8bcd5019745af818.html 這一個檔案似乎是和 Google 驗證有相關的
但內容不太確定與了解是什麼，所以想請問這個檔案是直接刪除就好了嗎？
2. 移除 bower.json 的部分，是連帶 gulpfile.js 中使用到 bower dependencies 的都要移除掉嗎？
想確定一下～～

**Comment by hashman** [comment]
> @hashman 有兩個問題想請問～
> 
> 1. google8bcd5019745af818.html 這一個檔案似乎是和 Google 驗證有相關的
>    但內容不太確定與了解是什麼，所以想請問這個檔案是直接刪除就好了嗎？

應該是沒問題，直接移除就好

> 2. 移除 bower.json 的部分，是連帶 gulpfile.js 中使用到 bower dependencies 的都要移除掉嗎？
>    想確定一下～～

如果確定 bower 沒有需要使用到那 gulpfile 中的相關程式也都可以一併移除，但需要先確定 bower 中 require 的幾個套件是否真的都可以被移除，或是可以採用別的方式 require

**Comment by FWcloud916** [comment]
@hashman 請問2017年的檔案還會再重新編譯(更新)嗎?
如果不會 就可以將跟 gulp 有關的檔案刪掉 (./tmp/vendor , gulpfile.js )

**Comment by hashman** [comment]
@FWcloud916 不會唷
