### ISSUE TITLE
協助確認官網優化建議之內容

### ISSUE THREAD

**Issue by hashman** [MOPCON/MOPCON#141]
https://docs.google.com/document/d/1VWIOx40rI5vVE3iWFXcZ9Z18rWX7ClO9eyyDsf2LkHk/edit

**Comment by hashman** [comment]
Sprint 2 繼續更新， @kaojane 記得 issue 這邊也要 update 狀況唷

**Comment by kaojane** [comment]
5/5 官網改良會議紀錄：
Q1首頁資訊不明確、缺少banner =>加入LOGO.標語.時間地點等元素 =>Resolve
Q2購票入口不清楚=>購票的按鈕可以用個不同色的button凸顯，加上右側懸浮的購票捷徑 =>Resolve
Q3分頁太多=>重新調整選單結構，待釐清今年要放的項目後陸續討論，例如加入周邊資訊等... 主標希望7個內  ) 
Q4講者資訊未有獨立連結=>目前有做不同參數的連結，可再加入左右切換紐=>Resolve
Q5相同公司下的相關資訊零散=>參考贊助wireframe頁面 可解決  =>Resolve
Q6網頁footer (底部資訊) 並未清楚提供媒體聯繫、活動贊助聯絡窗口=>
信箱改成統一contact@mopcon.org (文字+連結) 由行政組分派 其他可配合具體經營社群 =>Resolve
Q7MOPCON文章分享、相關資訊分散=> 改成以FB訊息為主=>Resolve (美術組可規劃呈現方式 )

其他針對首頁的討論：1.可列贊助講者，後續評估呈現的排序 2. 贊助商不用放首頁 3.保留地圖(可放最下方)

優化文件內容已解決，後續等美術組實際製作討論為主。

**Comment by hashman** [comment]
Hi @kaojane 這個 issue 還有任何的 update 嗎？或是可以將這個 issue close 呢？

**Comment by kaojane** [comment]
好的 可以close了 不過我帳號好像沒有出現close按鈕只能留comment 囧

**Comment by hashman** [comment]
沒關係，我來關就好，謝謝
