### ISSUE TITLE
協助規劃 CMS 講者 / 贊助商素材上傳頁面之規格

### ISSUE THREAD

**Issue by hashman** [MOPCON/MOPCON#142]
前台實作票

- （講者）https://github.com/MOPCON/Equipment-management-system/issues/53
- （贊助商）https://github.com/MOPCON/Equipment-management-system/issues/54

**Comment by kaojane** [comment]
詢問一下大家意見：
1.若有字數限制的欄位，是否可再輸入時就顯示目前字數/上限字數？超過有個提示之類的
2.是否做簡易的會員系統？目前想到的是講者/贊助商有可能有更新修改/補充資料需求？
(或者若不做會員的話，每次填表完給一組uid，之後可以用來登入修改？)

**Comment by hashman** [comment]
1. 可以做到沒問題
2. 我之前有個做法提議一下，因為要實作會員系統其實會比較麻煩一點，我在想可以產生一個 unique url 給廠商 / 講者與密碼，請他們在點選 url 的時候帶入密碼就可以使用，這樣就無需使用會員系統也可以達到保護

**Comment by hashman** [comment]
Sprint 2 繼續更新， @kaojane 記得 issue 這邊也要 update 狀況唷

這部分應該是可以先請前端開始設計了

**Comment by kaojane** [comment]
目前進度：
1.前台需求文件
https://docs.google.com/document/d/1vdx2N52TuFyNiZZ64fLH9C353QX5VBVWOEb5_FbT-Ug/edit
議程組剩譯成TAG未確認(95%) / 贊助組確認中
2.後臺需求文件 
先開立，內容待補
https://docs.google.com/document/d/1vBKg3qV4E5LjD0S9QPYoG1jKCw-O8eCAglO80plJ094/edit

**Comment by hashman** [comment]
ok 剛剛有將權限開給兩位前端了，等候兩位回應，先處理前台的部分，後台的文件再麻煩規劃了，謝謝

**Comment by kaojane** [comment]
https://docs.google.com/document/d/1vBKg3qV4E5LjD0S9QPYoG1jKCw-O8eCAglO80plJ094/edit
後台新增講者部分，目前想法如文件~~請hash幫忙看一下

**Comment by hashman** [comment]
我確認一下兩位後端工程師的狀況，如果沒問題，這個 issue 我覺得可以先 close 了

**Comment by hashman** [comment]
兩位後端工程師表示沒問題，就把這個 issue close 了
