### ISSUE TITLE
建立MOPCON IOS、Android開發者帳號

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/MOPCON#144]

**Comment by hashman** [comment]
Android 開發者帳號已經建立完畢且付費完成， iOS 尚無消息

**Comment by hashman** [comment]
Android APP 預計明天下午 miki 會進行移轉， iOS 的部分與 Keith 討論，還是等一下鄧白氏好了，依照蘋果官網的說明

If you are an individual or sole proprietor/single person business, your personal legal name will be listed as the seller on the App Store. Do not enter an alias, nickname, or company name as your first or last name, as entering your legal name incorrectly will cause a delay in the approval of your enrollment.

If you are a developer who is an employee at a company, non-profit organization, joint venture, partnership, or government organization, your organization’s legal entity name will be listed as the seller on the App Store and Mac App Store. We’ll ask for basic personal information, your legal entity name, and your D‑U‑N‑S® Number as part of our verification process. You can add additional developers to your team through the People page in your account on the developer website.

基本上 MOPCON 屬於 NGO 組織，且用個人的名義我無法只輸入 MOPCON ，我們還是耐心等一下好了

**Comment by hashman** [comment]
Android 已經完成了， iOS 鄧白氏電話驗證已經通過了，但他們說大概要等 2-4 週才會好... 只能等了

**Comment by hashman** [comment]
iOS 我看這個禮拜會不會有什麼進展，我這個禮拜會窮追猛打...

**Comment by hashman** [comment]
iOS Sprint 4 沒有移轉成功，繼續追殺中...

**Comment by hashman** [comment]
@bbandydd 我們先訂 7/8 如果沒有任何消息就請 iOS 那邊自行上架了？

**Comment by bbandydd** [comment]
> @bbandydd 我們先訂 7/8 如果沒有任何消息就請 iOS 那邊自行上架了？

@hashman ok, 另外這週UI沒提供的話，APP就先休息了，看了一下定版的大地遊戲沒特別功能要研究

**Comment by hashman** [comment]
> > @bbandydd 我們先訂 7/8 如果沒有任何消息就請 iOS 那邊自行上架了？
> 
> @hashman ok, 另外這週UI沒提供的話，APP就先休息了，看了一下定版的大地遊戲沒特別功能要研究

能否問一下 @kaojane 請他幫忙追蹤一下狀況？謝謝

**Comment by hashman** [comment]
應該算完成了，麻煩 @bbandydd 幫我看可否關掉了，謝謝
