### ISSUE TITLE
確認 Mopcon 2019 主辦社群資訊

### ISSUE THREAD

**Issue by kaojane** [MOPCON/MOPCON#162]
確認Mopcon2019主辦社群
是否與2018組織相同
https://mopcon.org/2018/community.php
或有增減

----

今年將參與年會工作的社群分為兩種：主辦社群、參與社群

定義社群角色：
===========
1. Organizer: 社群主要招集、規劃、創辦者
2. Co-Organizer: 社群共同規劃、創辦、招集者
4. 核心成員：社群的角度為 Organizer 與 Co-Organizer ，以 MOPCON 的角度為組長與副組長
3. 志工：有參與這個社群、研討會的志工即可（非參加者）
4. 參加者：參與社群活動者

定義主辦社群：
===========
1. 社群的核心成員有擔任 MOPCON 的核心成員者（組長、副組長、議程委員）
2. 社群志工有參與 MOPCON 志工團隊至少 3 人
3. 吻合上述者可被列名在 MOPCON 官網「主辦社群」頁面中

定義參與社群：
===========
1. 該社群有三位以上成員擔任當年度MOPCON志工
2. 該社群參與當年度社群攤位
3. 該社群當年度與MOPCON有合作周邊活動(例如workshop或是聯名社群聚會)
4. 對於濁水溪以南社群發展有卓著貢獻

社群應遵守項目：
===========
1. 社群僅能推廣社群文化或是開源精神
2. 社群不得進行商業推廣行為（如去年 Monospace 與 HonestBee 一樣）
3. 若違反上述者直接黑名單三年，不得再以社群名義參與 MOPCON 活動

調查方式：
請各組組長協助詢問自己 / 自己組內有沒有人是社群核心成員並希望列名為主辦社群之一

**Comment by hashman** [comment]
目前調查起來只有四個主辦社群一個參與社群

# 主辦社群

- GDG Cloud Kaohsiung
  - Organizer: Hash （資訊組組長）, Dada （場務組組長）, Puck （場務組組長）
  - 志工： UnciaX （場務組副組長）, Yuuna （場務組物流股股長）, 張景雲（資訊組組員）
- Kaohsiung Python User Group
  - Organizer: Victor （議程委員）, 品陞（副總召）
  - 志工： Terence Huang （議程委員）
- Python 量化投資
  - Organizer: Victor （議程委員）, 品陞（副總召）
  - 志工：培智（議程組副組長）
- ReactMaker
  - Organizer: Andy （資訊組副組長）, Hyman （資訊組組員）
  - 志工： Giant （資訊組組員）
- Agile Kaohsiung
  - Organizer: Gobby （副總召）, Scarlett （美術組組長）, Hermes （議程委員）

# 參與社群

- As A Product Designer
  - 志工： Zoe （美術組組員）, Andy Hugh （美術組組員）, Jason Liu （美術組組員）

**Comment by bbandydd** [comment]
ReactMaker算嗎？
Andy, Hyman, Giant參與Mopcon

**Comment by hashman** [comment]
> ReactMaker算嗎？
> Andy, Hyman, Giant參與Mopcon

算，我來補

**Comment by ofafa** [comment]
高雄敏捷應該也算？ Hermes(議程委員)、Gobby(副召)、Scarlett(美術組長)
HPX今年不知道有沒有志工參與就是了

**Comment by hashman** [comment]
> 高雄敏捷應該也算？ Hermes(議程委員)、Gobby(副召)、Scarlett(美術組長)
> HPX今年不知道有沒有志工參與就是了

@ofafa 可以算呀，但他們沒有提出所以就沒有寫到了，照上面看起來應該是 ok 的

**Comment by ofafa** [comment]
好 HPX我問Egg看看

**Comment by ofafa** [comment]
核心成員：社群的角度為 Organizer 與 Co-Organizer ，以 MOPCON 的角度為組長與副組長、`議程委員`

**Comment by hashman** [comment]
> 核心成員：社群的角度為 Organizer 與 Co-Organizer ，以 MOPCON 的角度為組長與副組長、`議程委員`

ok 我補上去了，名單就這先先提交，之後如果有要新增的話再上 patch 就好

**Comment by mosquitojoe85** [comment]
不好意思，我補一下主辦社群的議程委員部分，

- 高雄前端社群：廖洧杰
- PyTorch Kaohsiung：Terence Huang

**Comment by hashman** [comment]
> 不好意思，我補一下主辦社群的議程委員部分，
> 
> * 高雄前端社群：廖洧杰
> * PyTorch Kaohsiung：Terence Huang

HI 你好，不好意思看帳號不知道是哪位，能否自我介紹一下呢？另外是主辦社群的規範麻煩可以參考上方之規定辦法唷

**Comment by mosquitojoe85** [comment]
喔喔，我是 Brook。
