### ISSUE TITLE
確認 MOPCON 2019 官網語系切換的方式

### ISSUE THREAD

**Issue by hashman** [MOPCON/MOPCON#164]
過往是透過 https://mopcon.org/2019?lang=zh/en 來進行語系的設定，並且將設定語系存在 Cookie 中，此外 API 所提供的內容也是不分中英文全丟給給 Client 讓 Client 進行判斷

2019 開始，我們已經走向前後端分離的架構，後端僅提供 API 給 APP / Web 進行使用，語系的控制方式可能要調整一下，以下提供幾個做法

1. 保持原狀， API 提供所有的欄位讓 Client 自行判斷，語言檔也是放在 Client 存放
2. API 提供相對語系的語言檔，除了 API 資料的語系將會由 Client 指定語系請後端提供，另外 Client 上所呈現的文字也由後端提供字典檔（當然 Client 可以做 Cache 不用每次都跟 Server 要）

會提出 2 主要有幾個原因
1. 讓 APP 方便，過往語言檔在 APP 上如果要修改就要重新送審，麻煩，但相對放在 local 就是快
2. 所有平台文字統一， Web / APP 統一顯示文字，沒有平台的差異，也不會出現一個平台改了，另外一個平台沒有改的問題

以上提出讓大家選擇，又或者可以提出其他的方案也可以

**Comment by hashman** [comment]
請各位上來這邊 comment 提供意見與想法，謝謝

**Comment by xwang0929** [comment]
2

**Comment by Wuchiwei** [comment]
2

**Comment by bbandydd** [comment]
2

**Comment by ghost** [comment]
2

**Comment by keith222** [comment]
2

**Comment by Tzuhui** [comment]
2

**Comment by FWcloud916** [comment]
2

**Comment by Zames-Chang** [comment]
2

**Comment by chnbohwr** [comment]
2

**Comment by hashman** [comment]
這部分看起來大家都有共識了，之後就麻煩 APP team 的朋友依照功能開需求給 Web team 的朋友來增加 APi 謝謝
