### ISSUE TITLE
協助開發 Facebook 粉絲專頁最新動態 API

### ISSUE THREAD

**Issue by hashman** [MOPCON/MOPCON#166]
目前於 #163 首頁抓取 Facebook Fan Page 最新動態是使用 https://www.juicer.io 來達成，如 https://github.com/MOPCON/MOPCON/pull/163#pullrequestreview-256056606 這邊說明，希望還是使用自行開發的元件來進行使用

這邊需要後端協助研究 Facebook API 來進行取得資料轉送給前端進行使用

這個也先掛給 Zames 有問題可以隨時討論

**Comment by hashman** [comment]
@Zames-Chang Sprint 5 先以研究為主， Sprint 6 再進行開發，或是再看看情況調整，謝謝

**Comment by Zames-Chang** [comment]
> @Zames-Chang Sprint 5 先以研究為主， Sprint 6 再進行開發，或是再看看情況調整，謝謝

我剛剛研究了一下 Facebook Api，他們那邊如果要讀取粉絲專頁的公開po文必須要申請他們的facebook developer 的帳戶，且透過這個帳戶去申請可以存取粉絲專頁公開資料的權限（審核日約5天)。

過程挺麻煩的，要滿足這個網站說的所有條件
[facebook 認證](https://developers.facebook.com/docs/apps/review)

沒有申請到的話，好像不能隨意存取粉專的公開貼文。

@hashman

**Comment by hashman** [comment]
幫我看一下這個可不可以，但直覺不行，但我還沒看 source code

https://rsshub.app/facebook/page/mopcon

https://github.com/DIYgod/RSSHub

**Comment by Zames-Chang** [comment]
> 幫我看一下這個可不可以，但直覺不行，但我還沒看 source code
> 
> https://rsshub.app/facebook/page/mopcon
> 
> https://github.com/DIYgod/RSSHub

ok 我研究看看

**Comment by Zames-Chang** [comment]
我用單純擷取html的方式，看起來沒辦法拿到資料，研究了一下發現說他前端的貼文好像是進去之後再透過js去render出來的，不是一開始get的時候就傳過來。

那後來我又有想說那我用 selenium 之類的東西等他render完再去抓他的資料好了，但是這樣又有一些問題
1. 很髒，其實根本不知道每台電腦要等他render多久才去抓資料下來
2. 我發現他抓下來的資料跟我自己用chrome console的結果不一樣orz（這部分可能是我自己程式寫錯還在看是啥問題）

**Comment by bbandydd** [comment]
是要從fb 粉絲專頁抓文章透過api給前端的意思嗎？？

**Comment by Zames-Chang** [comment]
> 是要從fb 粉絲專頁抓文章透過api給前端的意思嗎？？

Yes

**Comment by hashman** [comment]
這塊有點搞剛，我們先 pending 好了，我希望可以先規劃其他頁面的 API 讓 APP / 前端可以先串接了

**Comment by Zames-Chang** [comment]
@hashman  我已經根據你的要求做修改了，麻煩你再看一下
[#181 ](https://github.com/MOPCON/MOPCON/pull/181)

**Comment by hashman** [comment]
Hello @Zames-Chang 目前前端在 #185 上面進行串接，在需求上希望可以在 api 上面多露出幾個資訊

1. 按讚人數
2. 分享人數
3. 回傳 url 讓前端可以連結過去

以上請 Zames 幫忙研究可否做到，謝謝

**Comment by Zames-Chang** [comment]
我研究過了，都可以做到
1. 按讚人數(單純按讚人數我可以做到，但是因為fb現在不只有讚還有haha 等其他表情，我有試著把所有情緒的資料調出來看看但沒實驗成功，但是單純按讚人數的話是ok的。)
2. 分享人數(OK)
3. 回傳 url 讓前端可以連結過去(OK)

**Comment by hashman** [comment]
> 我研究過了，都可以做到
> 
>     1. 按讚人數(單純按讚人數我可以做到，但是因為fb現在不只有讚還有haha 等其他表情，我有試著把所有情緒的資料調出來看看但沒實驗成功，但是單純按讚人數的話是ok的。)
> 
>     2. 分享人數(OK)
> 
>     3. 回傳 url 讓前端可以連結過去(OK)

ok 直接 go 吧

**Comment by hashman** [comment]
Done
