### ISSUE TITLE
上了 FB Like 之後，版面輪子亂了

### ISSUE THREAD

**Issue by cdchen** [MOPCON/MOPCON#17]
![google chrome](https://f.cloud.github.com/assets/427313/643927/d7ac331a-d380-11e2-8188-b25415db3c08.png)

OS: MacOS X 10.8
Browser: Chrome 27

**Comment by weitsai** [comment]
將CSS fb-lix box  的 TOP 拿掉即改善

**Comment by cdchen** [comment]
我來處理好了，謝謝 Webbertsai，您是最棒的!!

**Comment by cdchen** [comment]
Fixed by webbertsai.
