### ISSUE TITLE
規劃 / 製作 贊助商頁面 API

### ISSUE THREAD

**Issue by hashman** [MOPCON/MOPCON#171]
贊助商列表
https://drive.google.com/open?id=1JrI1eEo6cC0lRKRFq4aq-hPso9lEwxv8
贊助商資訊
https://drive.google.com/open?id=16pBlm_4-aiVeh8YFjiNjcclnWFmwrP1b

https://d.pr/i/ZaQ5m2

(若有更新以https://zpl.io/Vx6jDOx為主)

**Comment by hashman** [comment]
這個請 Zames 處理，請 @kaojane 幫忙補充一些內容，謝謝

**Comment by kaojane** [comment]
補充web版贊助商UI也已確認
https://drive.google.com/drive/folders/1cIW1YHqtsq4Mt--xZB1RaLsJsowqaSVT

**Comment by hashman** [comment]
> 補充web版贊助商UI也已確認
> https://drive.google.com/drive/folders/1cIW1YHqtsq4Mt--xZB1RaLsJsowqaSVT

這個好像不是最新的，我記得設計有一些微調，再麻煩 Jane 更新一下，謝謝

**Comment by kaojane** [comment]
我拉了最新的下來 
Web
https://drive.google.com/open?id=1yj8BWJHkMKBl-wfoN1zstJshKPh03Khr
Mobile
https://drive.google.com/open?id=1HXl3f3zdL5IFnn1PPMnRYrC6-mJQa9Vf
說明書
https://drive.google.com/open?id=1rDVkdlAA68IZQQFn-wbwEPq2kjvwsTga
