### ISSUE TITLE
規劃 / 製作 講者頁面 API

### ISSUE THREAD

**Issue by hashman** [MOPCON/MOPCON#172]

**Comment by kaojane** [comment]
更新UI

WEB版
https://drive.google.com/drive/u/2/folders/1BiDV-kD316JkjSqH0IdQuNDI_THh1g7P
APP
https://drive.google.com/open?id=15r1m8_SQPx9lTNVCACOLA1D-SeUavr1T
https://drive.google.com/open?id=1tQ3tO7hfshNUISAQSdq2A-E0zrQcNlED
(若有更新以https://zpl.io/Vx6jDOx為主)

web補充：
分享講者的按鈕點擊後為複製連結
tag的顏色目前是依照類型，技術類 → 藍色、設計類 → 綠色、其他 → 紅色

**Comment by hashman** [comment]
這個請 @Zames-Chang 幫忙處理，謝謝

**Comment by hashman** [comment]
這個比較趕，我來處理

**Comment by hashman** [comment]
這個結束了
