### ISSUE TITLE
增加網站meta描述與FB分享圖

### ISSUE THREAD

**Issue by kaojane** [MOPCON/MOPCON#176]
增加如下
``
<meta name="description" content="MOPCON 2019 堅持濁水溪以南，南台灣最大行動科技年會，10/19-10/20 高雄國際會議中心與您見面。持續匯集知識與人才，打造高速資訊交流圈，提升個人與團隊價值，讓知識影響正向循環。" />
<meta property="og:description" content="MOPCON 2019 堅持濁水溪以南，南台灣最大行動科技年會，10/19-10/20 高雄國際會議中心與您見面。持續匯集知識與人才，打造高速資訊交流圈，提升個人與團隊價值，讓知識影響正向循環。" />
<meta property="og:image" content="圖片網址" />
``
圖片請使用以下這張圖片
https://drive.google.com/drive/folders/1WU7JCtjNWCZ_t9WraHSoHctTWWkV7stU
不知道為什麼格式怪怪的 每段meta一行即可

**Comment by hashman** [comment]
Reference MR: https://github.com/MOPCON/MOPCON/pull/177

**Comment by hashman** [comment]
@kaojane 推上去了，幫我驗證一下，謝謝

https://dev.mopcon.org/2019/

**Comment by kaojane** [comment]
OK
雖然圖片好像不是我原本傳這張XD
不過更好看一點~
