### ISSUE TITLE
KSDG wording & logo 更新

### ISSUE THREAD

**Issue by ericpi** [MOPCON/MOPCON#18]
![ksdg-logo-new_mopcon](https://f.cloud.github.com/assets/80681/647013/3380bf0a-d3f2-11e2-8dda-3be71e9e15bc.png)

Wording 如下:

Kaohsiung Software Developer Group 是高雄從事軟體開發、網路技術開發者一起交流的園地，2012/05首度聚會活動，目前每月舉辦 Meet-up 及 Web Course 各一場，交流主題涵蓋各種軟體技術，歡迎對軟體開發技術有興趣的朋友可以踴躍參與。

**Comment by weitsai** [comment]
@ericpi 已更新 https://github.com/MOPCON/MOPCON/commit/053a355a29e0746615ee7ea44ee8f4ef01462e08

**Comment by cdchen** [comment]
@webbertsai  2013 的部份，也要麻煩您 update 一下唷!!

**Comment by cdchen** [comment]
@webbertsai  收到，您是最棒的，太厲害了!!
