### ISSUE TITLE
後端 API 開發流程

### ISSUE THREAD

**Issue by hashman** [MOPCON/MOPCON#189]
# 目標

開此 issue 主要目的為傳達後端建構 API Document 之流程，讓 PM / 工程師可已有更為順暢的流程之外，也讓後端工程師 / 前端工程師 / APP 工程師溝通起來更為流暢

# 工作流程說明

1. 請 PM / 組長協助將設計師已經設計完成的畫面截圖開 issue ，將此 issue assign 給 @hashman 進行需求確認
2. 確認需求沒問題將 issue assign 給後端工程師進行規劃與開發
3. 工程師規劃時可以參考此 [PR](https://github.com/MOPCON/Equipment-management-system/pull/98) 之內容進行 API Spec 規劃
4. 撰寫出 API Spec 給前端 / APP 確認是否有問題
5. 開始開發 API ，開發不一定要完整開發完成，若時程上有壓力可以先開出 mock API 給前端 / APP 進行串接
6. 前端 / APP 完成串接

# 開發細節注意

1. API 需要注意 response time 每個 request 最好都可以在 500ms 內完成，超過則個案討論是否有優化的機會
2. 減少 server loading 建議可以採用 cache server 的方法，像是 redis, memcache 等服務來輔助，達到更好的使用者體驗

如果有其他的問題歡迎大家 comment 來討論，希望可以幫助大家未來合作上更為順暢，謝謝

**Comment by xwang0929** [comment]
ok

**Comment by FWcloud916** [comment]
ok

**Comment by Wuchiwei** [comment]
ok

**Comment by kaojane** [comment]
OK

**Comment by keith222** [comment]
ok

**Comment by Tzuhui** [comment]
ok

**Comment by bbandydd** [comment]
ok

**Comment by chnbohwr** [comment]
ok

**Comment by Zames-Chang** [comment]
ok

**Comment by ghost** [comment]
ok

**Comment by hashman** [comment]
Ok 謝謝
