### ISSUE TITLE
協助確認各組介紹詞

### ISSUE THREAD

**Issue by hashman** [MOPCON/MOPCON#190]
#170 

目前資訊組正在著手進行主辦社群 / 工作人員頁面工作，需要麻煩組朋友提供給我各組的介紹詞

如果不知道要寫什麼可以參考 [去年的至工組織頁面](https://mopcon.org/2018/volunteer.php)

如果沒有 Github 帳號無法留言者，你可以選擇申請一個 Github 帳號或是直接於 Slack 中留言跟我說，我來幫你填寫

謝謝

**Comment by dada8397** [comment]
場務組：場地之守護神，照料與會者的一切，為工人把屎把尿。場地的一切柴米油鹽醬醋茶都是我們負責。

**Comment by Sandra66628** [comment]
公關組：可比喻為魔術師！為震撼觀眾的身心靈而努力。我們是一群什麼都要有梗，而且沒有梗，毋寧死的生物！

**Comment by hashman** [comment]
財務組：錢跟收據的來來去去。

**Comment by s1hon** [comment]
錄影組：為大家記錄講者講到口沫橫飛、會眾眼睛脫窗之間的起承轉合。好歹，之後我們能一邊拿出來膜拜或拿出來笑。

**Comment by RainrainWu** [comment]
贊助組：謝謝各位的支持！謝謝！謝謝！謝謝！

**Comment by Chung-Wei-Pan** [comment]
議程組：各場議程的守護神，致力於尋找各路大神，為的就是打造獨一無二的 MOPCON 宇宙！

**Comment by hashman** [comment]
總召組：輔導長、喚醒師、撩癒姐、業務哥組成，完成各種推坑於無形的工作，讓混亂中建立優雅，在平實中製造刺激，使停留中促進前進，這就是本組的日常。

**Comment by hashman** [comment]
美術組： MOPCON 門面就靠我們了！從網站、 APP 、紀念品等大大小小事情都包辦，組別有來自全台灣各式各樣的人才，一起共創每年新體驗～

**Comment by klin0816** [comment]
攝影組：把每一個珍貴的瞬間轉變成永遠！在 MOPCON 會議上拿著一台又一台大砲隨時備戰，看到我們記得微笑，這樣就會有美美的照片出現了哦！
