### ISSUE TITLE
規劃 / 製作APP首頁 API

### ISSUE THREAD

**Issue by kaojane** [MOPCON/MOPCON#192]
APP首頁設計稿
https://drive.google.com/file/d/17kYyc4U87ekQSHtxys1_DyBGmAtuOqi0/view?usp=sharing
(若有更新以https://zpl.io/Vx6jDOx為主)

**Comment by hashman** [comment]
這個 API 跟 #205 與 #199 有關，等候兩個 issue 處理完再處理這個

**Comment by hashman** [comment]
這個請 @FWcloud916 幫忙，一樣這個禮拜五之前先產出 API Document 進行討論，這邊麻煩幫忙了，謝謝
