### ISSUE TITLE
協助確認講師 / 贊助商 CMS Testing 環境測試狀況

### ISSUE THREAD

**Issue by hashman** [MOPCON/MOPCON#193]
預計測試到 8/9 請 Jane 幫忙

**Comment by hashman** [comment]
這個麻煩 @kaojane 幫我 confirm 一下是否已經 ok 了，如果沒問題就把這個 issue 關閉，謝謝

**Comment by kaojane** [comment]
web這邊我好像沒有權限~不過是可以關閉了沒錯
