### ISSUE TITLE
規劃與製作 APP Initial Config API

### ISSUE THREAD

**Issue by hashman** [MOPCON/MOPCON#194]
目前我希望在 APP Initial 的時候可以先 call 這隻 API 這個 API 主要會回傳幾個東西

1. APP 可不可以使用大地遊戲，主要在這次大地遊戲的 API 會開在新的機群上面，所以活動結束後就會把機群關掉，為了不影響 APP 其他功能進行，所以會將大地遊戲的選項關閉
2. 各個 API Server 的 url ，這次可能不只是有 https://mopcon.org 的 api 還有大地遊戲 or 可能也會需要使用 CMS 的 API ，所以需要提供 config 讓 APP 知道什麼 API 該打到那個 url 上面
3. 提供語言檔？根據之前的討論 APP 上面所呈現的內容可能會由 API 來提供，這樣就不用因為修改 wording 而需要重新審查 code

如果 APP Team 的朋友有想到其他的內容可以隨時幫我補充

**Comment by Wuchiwei** [comment]
> 2. 各個 API Server 的 url ，這次可能不只是有 https://mopcon.org 的 api 還有大地遊戲 or 可能也會需要使用 CMS 的 API ，所以需要提供 config 讓 APP 知道什麼 API 該打到那個 url 上面

這個需求是源自於我們的 API Server 會動態變動嗎？不然雖然有很多台不同的 server，只要不會動態變動，可以把 API 寫在 app 裡就好

**Comment by hashman** [comment]
> > 1. 各個 API Server 的 url ，這次可能不只是有 https://mopcon.org 的 api 還有大地遊戲 or 可能也會需要使用 CMS 的 API ，所以需要提供 config 讓 APP 知道什麼 API 該打到那個 url 上面
> 
> 這個需求是源自於我們的 API Server 會動態變動嗎？不然雖然有很多台不同的 server，只要不會動態變動，可以把 API 寫在 app 裡就好

@Wuchiwei 原則上不會，但想說都已經有這個 API 的存在了，就一起提供， domain name 原則上講好了就是不會換，就算會換也會從 DNS 那邊下手，不會直接改 domain
