### ISSUE TITLE
規劃 / 製作APP議程資訊 API

### ISSUE THREAD

**Issue by kaojane** [MOPCON/MOPCON#197]
APP議程資訊設計稿
https://drive.google.com/open?id=1QpPpszjMlN8sEX_VOXV4Orxnown48G2d
(若有更新以https://zpl.io/Vx6jDOx為主)

此外 Web 的部分也規劃完畢了，詳細可以參考 Zeplin

**Comment by hashman** [comment]
這個請 @FWcloud916 幫忙處理，謝謝

**Comment by hashman** [comment]
這個都完成了
