### ISSUE TITLE
規劃 / 製作APP贊助商列表&贊助商資訊 API

### ISSUE THREAD

**Issue by kaojane** [MOPCON/MOPCON#198]
贊助商列表
https://drive.google.com/open?id=1JrI1eEo6cC0lRKRFq4aq-hPso9lEwxv8
贊助商資訊
https://drive.google.com/open?id=16pBlm_4-aiVeh8YFjiNjcclnWFmwrP1b

(若有更新以https://zpl.io/Vx6jDOx為主)

**Comment by hashman** [comment]
與 #171 重複囉，我將這個關閉
