### ISSUE TITLE
規劃 / 製作APP主辦社群列表&主辦社群資訊 API 

### ISSUE THREAD

**Issue by kaojane** [MOPCON/MOPCON#201]
主辦社群列表
https://drive.google.com/open?id=1TeSXYj8SVRD6JhS8_j0oZRHHI8yqrNFG
主辦社群資訊
https://drive.google.com/open?id=1rbqmTX4hnDFUJ3fVGu6tST-itVxRDMem
(若有更新以https://zpl.io/Vx6jDOx為主)

**Comment by hashman** [comment]
與 #170 重複了，就把這個 issue 關閉
