### ISSUE TITLE
規劃 / 製作APP志工組織列表&志工組織資訊 API 

### ISSUE THREAD

**Issue by kaojane** [MOPCON/MOPCON#202]
志工組織列表
https://drive.google.com/open?id=1WC9ZN22iHrDWEUw9-hTXQUtVNNFwgiSE
志工組織資訊
https://drive.google.com/open?id=1lKv9GiR8-1BrKb7dF9FcEitSqESC6DYZ
(若有更新以https://zpl.io/Vx6jDOx為主)

**Comment by hashman** [comment]
目前這個需求確定了嗎？

**Comment by kaojane** [comment]
確認的，不過發現應該跟這則重複 https://github.com/MOPCON/MOPCON/issues/170

**Comment by hashman** [comment]
#170 有安排工程師與設計師進行規劃了，這個 issue 就將他關閉
