### ISSUE TITLE
規劃 / 製作APP交流場次 API 

### ISSUE THREAD

**Issue by kaojane** [MOPCON/MOPCON#203]
交流場次資訊
https://drive.google.com/open?id=1_kcrbveAp-IaOZtmuwXneyVGZ53QkoFc
(若有更新以https://zpl.io/Vx6jDOx為主)

**Comment by hashman** [comment]
目前這個需求確定了嗎？

**Comment by kaojane** [comment]
https://mopcon.slack.com/archives/CJ0U8A0SW/p1564018502039800
我看之前討論串是說可用兩個入口的方式做
(一個合併於議程表，一個為單獨的交流場次)
若沒有其他的疑慮應該是可以照設計目前的規劃

**Comment by hashman** [comment]
主要是目前 UI 上面的介面並未設計完成，所以會讓工程師不確定明確的需求而無法進行 API Spec 設計，我們可能需要等設計的 wireframe 出爐後才比較容易讓工程師進場

**Comment by kaojane** [comment]
@hashman  那我需要再問一次美術組andy目前是不是除大地遊戲以外頁面都final了嗎(因為我這邊也是抓他更新過的版本)?

**Comment by hashman** [comment]
麻煩你了，謝謝

**Comment by kaojane** [comment]
跟設計師確認這個是final版了~
至於有一行"交流場次的文案顯示於此"，目前沒有文案的規劃，可以拿掉即可

**Comment by hashman** [comment]
這個請 @Zames-Chang 幫忙處理，謝謝

**Comment by hashman** [comment]
這個完成了
