### ISSUE TITLE
官網的贊助按鈕加總好像有點問題

### ISSUE THREAD

**Issue by Mikimoto** [MOPCON/MOPCON#24]
剛剛看到他居然沒有把 FB 的數字加入？

**Comment by cdchen** [comment]
這個問題，是因為我在首頁上抓的是 "http://mopcon.org" 的網址之按讚數，同樣的 G+ 也是抓 "http://mopcon.org"。所以，要改成「粉絲團」與「Google Page」的嗎??

**Comment by ericpi** [comment]
我會比較建議用粉絲群跟 Google Page 的數字, 除非官網經營很成功有其他附加功能, 不然粉絲群跟 Google Page 流動率跟追蹤狀況會優於官網

**Comment by cdchen** [comment]
現在有個問題，我用的那個 Plugin，僅支援單一個網址。換句話說，沒有辦法同時抓 Facebook Fans Page 與 Google Page 的 URL 做 Recommend。不知道兩位前輩有沒有什麼建議??

**Comment by cdchen** [comment]
fixed.
