### ISSUE TITLE
贊助頁面缺 KaLUG

### ISSUE THREAD

**Issue by cdchen** [MOPCON/MOPCON#29]
缺 KaLUG 下列東西：
1. Logo
2. Official URL.

麻煩請相關人員提供，謝謝!!

**Comment by ericpi** [comment]
1. logo 可以用官網(246x154)的來 resize: http://kalug.linux.org.tw/pmwiki/pub/skins/pmwiki/kalug_draft.png
2. KaLUG 官網: http://kalug.linux.org.tw/

**Comment by cdchen** [comment]
fixed.
