### ISSUE TITLE
KSDG logo 2012/2013 不同底色

### ISSUE THREAD

**Issue by ericpi** [MOPCON/MOPCON#31]
http://mopcon.org/2012/social.php
http://mopcon.org/2013/social.php

可能要麻煩都用白底比較好, 感謝.

**Comment by cdchen** [comment]
這個我建議由美術組來做最後定奪。謝謝 @ericpi !!

**Comment by Mikimoto** [comment]
Donna 那邊說用白底

請用白底
理由一： KSDG灰底容易被忽略
理由二：MOSUT看起來跟其他logo不和

**Comment by cdchen** [comment]
fixed.
