### ISSUE TITLE
修改主辦社群頁面的志工名稱

### ISSUE THREAD

**Issue by puckwang** [MOPCON/MOPCON#314]
目前官網上的主辦社群頁面中，有部分志工為真實姓名，是否應該有填暱稱的優先使用暱稱比較好？

**Comment by hashman** [comment]
請 @Zames-Chang 幫忙處理，資料在 [這邊](https://docs.google.com/spreadsheets/d/1NsSLPhtnD77-5B1TIEidsSq4QeYoeevnSR8O9fNi6r4/edit#gid=0) 如果有暱稱就以暱稱為主

**Comment by hashman** [comment]
修正上去了
