### ISSUE TITLE
官網 by 用戶帶 utm 參數至 KKTIX 一般售票頁面

### ISSUE THREAD

**Issue by zaoldyeck** [MOPCON/MOPCON#323]
## 優先度
**重要** 且 **緊急**

## 需求情境
1. 目前已售出 426 張票（10/3），起碼還要售出 >200 張票才會符合我們與贊助商的期望
2. 接下來會用廣告投放的方式來催票

## 廣告投放的用戶體驗流程
1. 用戶在 FB 看到廣告
2. 點擊廣告內容
3. 進入 MOPCON 官網[首頁](https://mopcon.org/2019/ )
4. 點選網站中的購票按鈕
5. 進入 KKTIX [一般票](https://kktix.com/events/2019registernormal/registrations/new)購票頁面
6. 選擇票種
7. 購票

## 目前問題
1. 廣告會需要優化，優化就會需要知道每一則文案的績效
2. 知道文案績效的方法，就是用 [utm 參數](https://www.awoo.com.tw/blog/utm/)做紀錄，並且用 Google Analytics 做追蹤（可參考[教學](https://drive.google.com/drive/u/2/folders/11bjMpFnW2lzxO5KPY8vD3jH4Cai-JISf)）
3. 由於預計的售票用戶體驗是採兩段式（用戶先進入 MOPCON 官網、再點擊購票按鈕進入 KKTIX），在 MOPCON 官網轉址進 KKTIX 的過程中，utm 參數會消失，這樣就會無法追蹤訂票究竟是由哪一則貼文或廣告帶來的

## Q&A
1. 為什麼不採用一段式，讓用戶直接導到 [KKTIX](https://mopcon.kktix.cc/events/2019registernormal) 就好？
Ans：經過我們在 GA 中的分析，直接進入 KKTIX 購票頁面的流量，流失率非常高。其催票的效果不入官網[首頁](https://mopcon.org/2019/)來得好 

## 期望解法
1. 當帶 utm 參數的用戶進入 MOPCON 官網，之後點擊購票按鈕時，會把原本帶進官網的 utm 參數透過 url parameters 一併帶入 KKTIX 購票[頁面](https://kktix.com/events/2019registernormal/registrations/new)
2. utm 的參數有 `utm_source`, `utm_medium`, `utm_campaign`, `utm_term`, `utm_content` ，可參考[文件](https://ga-dev-tools.appspot.com/campaign-url-builder/)

## 範例
1. 用戶 A 透過廣告進入 MOPCON 官網，網址為 `https://mopcon.org/2019/?utm_source=fb&utm_medium=ad&utm_campaign=here_we_con`
接著點擊首頁的購票按鈕，或是票種介紹頁面中的老鳥票 or 一般票 or 團購票，網站會將他轉址到 `https://kktix.com/events/2019registernormal/registrations/new?utm_source=fb&utm_medium=ad&utm_campaign=here_we_con`

## 實作規格：
- MVP（最小可行性版本）
  - 需儲存帶入 utm 參數的頁面
    - https://mopcon.org/2019/
    - https://mopcon.org/2019/ticket/
  - 需轉址到 KKTIX 的頁面
    - https://kktix.com/events/2019registernormal/registrations/new （對應會眾、老鳥、團購票）
- 完整版
  - 儲存進入官網任一頁面的 utm 參數
  - KKTIX 一樣處理一般票種即可（之後只會針對一般票種發文案），明年則不一定會繼續用 KKTIX 做售票平台

### 其他
- 官網上所有的`我要購票`懸浮按鈕，一律轉址到 
 `https://kktix.com/events/2019registernormal/registrations/new`，並帶 utm 參數
- 在票種介紹[頁面](https://mopcon.org/2019/ticket/)
  - 將老鳥票、會眾票、相揪團購票的轉址改為 `https://kktix.com/events/2019registernormal/registrations/new`，並在用戶點擊時帶入 utm 參數
  - 豪華獨享票、尊爵不凡票的轉址改為`https://kktix.com/events/2019registervip/registrations/new`
  - 將`Beengaged 醞釀之夜`票種改為`已完售`，並不再有超連結

## 測試工具
[Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna)

**Comment by Tzuhui** [comment]
@zaoldyeck 想問一下～
是否需要把參數存起來，在換頁之後還會記錄著 utm，並帶到購票的 url 中？
還是只要換頁後就不記錄？

**Comment by zaoldyeck** [comment]
是的，在官網換頁仍要記住，可以不顯示在網址上，但一旦連到 KKTIX 時就要把 utm 參數帶入網址。
