### ISSUE TITLE
Social Network 網址列表及G+ 連結官網

### ISSUE THREAD

**Issue by ericpi** [MOPCON/MOPCON#34]
目前官網好像沒有地方揭露所有 SNS 網址? 是否首頁找個小區域(例如三個文字區塊的下緣)規劃一個 follow us 的連結區域呢?
FB: https://www.facebook.com/mopcon
G+: https://plus.google.com/116768206884057057248
Twitter: https://twitter.com/mopcon

另外 Google+ Page 要連結官網需要首頁任何一處放入以下程式碼, 所以可以跟以上一起規劃囉.
&lt;a href="https://plus.google.com/116768206884057057248" rel="publisher"&gt;Google+&lt;/a&gt;

**Comment by cdchen** [comment]
如果有多個 SNS Link，小弟建議拿掉 Sharrre 這個 Plugin，另外自己寫。但，這無法在這一兩天時間內完成，因為最近這兩週小弟會比較忙... 誰願意跳下來的呢??

**Comment by ericpi** [comment]
其實我覺得 Sharrre 跟 SNS 連結不衝突, 可以用以下方式置於右下角或是左下角文字區塊下方, eg:

![sns-sample](https://f.cloud.github.com/assets/80681/679447/d4c4f41e-d968-11e2-8b76-ccfecd6c5480.png)
