### ISSUE TITLE
M娘 404 官網頁面

### ISSUE THREAD

**Issue by evan3rd** [MOPCON/MOPCON#36]

**Comment by CQD** [comment]
所以原來的失蹤兒童就拿掉了...?

**Comment by Mikimoto** [comment]
是的，麻煩囉

**Comment by CQD** [comment]
![2013-07-22 1 50 43](https://f.cloud.github.com/assets/94944/832069/22147fc2-f22e-11e2-9040-d852d401c094.png)

Done, 看起來大概是這種感覺...

**Comment by evan3rd** [comment]
辛苦你了，我覺得很棒

看你是直接放到 develop 或你 push 到新的 branch 都可以

2013/7/22 CQD notifications@github.com

**Comment by CQD** [comment]
先推到 develop 了

不過剛剛用另外一台機器開了一下，版面跑掉了。
看了一下似乎是原本 all.css 跟 bootstrap 不會被套用到頁面上，結果在某些情況下會被套到。

先上了一個 hotfix 讓版面不會跑掉，細節晚上回家來研究。

**Comment by Mikimoto** [comment]
CQD++ , 很棒喔

**Comment by CQD** [comment]
因為 include head 裡面會套用 bootstarp 跟 all.css，但是 404 的 URL 下面不一定有，然後變成 all.css 的 404，自動 redirect 給 2012/ 下的 all.css

然後因為 404.php 一開始有送 html comment，所以有可能送出 302 redirect 也可能送不出來...

處理方法
- 讓 404 頁面不論有沒有被套用到 bootstrap 跟 all.css 看起來都差不多
- 拿掉 404.php 開頭的 html comment 換成 PHP comment，避免 redirect 失敗

改好推上 develop 了
