### ISSUE TITLE
Call for Paper 相關頁面

### ISSUE THREAD

**Issue by evan3rd** [MOPCON/MOPCON#37]
Call for Paper 文件出爐，請上網頁，需要頁面介紹、Call for Paper 網址鏈結跟提供 Link 下載 CFP 文件

**Comment by CQD** [comment]
cfp.php 以及 MOPCON-CallForPaper.pdf 推上 develop

Bootstrap-ish，應該還 OK...

**Comment by CQD** [comment]
BTW，還沒放上 navbar，registrano 的報名連結還沒開放的樣子。

**Comment by jserv** [comment]
Added myself for tracking CfP

**Comment by jserv** [comment]
PDF is not synchronized to the latest version so far.

**Comment by CQD** [comment]
文件更新了。

BTW，報名連結 http://registrano.com/events/MOPCON2013-cfp 有預定開放的時間嗎？

**Comment by CQD** [comment]
Urr...pdf 裡面的 registrano 連結有問題，會連到 coscup 的 Call for Paper..

我用手上的 Mac 版 Word 存檔會有字變成方塊，有人方便幫忙解決的嗎？

**Comment by Mikimoto** [comment]
我幫忙處理，另外也開一個 cfp 資料夾做 call for paper 文件同步

**Comment by Mikimoto** [comment]
Eric 建議：
- 議程投稿頁面, tab會壓按在贊助頁
- cfp文件、registrano投稿頁面, 都請用開新頁面開啟
- 前往 http://registrano.com/events/MOPCON2013-cfp 投稿 ===> 建議用按鈕連結方式: 
  <a class="btn btn-success btn-large" target="_blank">href="http://registrano.com/events/MOPCON2013-cfp">前往投稿</a>
- CFP部分建議美化一下, 可以用 CFS 同樣風格的 header/footer 色塊, 另外建議夾入一兩張 2012 活動圖

**Comment by Mikimoto** [comment]
上線
