### ISSUE TITLE
MOPCON 文字轉播使用 Logbot 來做現場實況轉播

### ISSUE THREAD

**Issue by Mikimoto** [MOPCON/MOPCON#38]
類似這樣的效果

http://logbot.g0v.tw/channel/g0v.tw/today

套件應該是

https://github.com/dannvix/Logbot

**Comment by ericpi** [comment]
node.JS 版本的 irc bot:
https://github.com/draggor/node-ircbot
https://github.com/ktiedt/NodeJS-IRC-Bot

**Comment by Mikimoto** [comment]
有沒有 Demo 可以看啊？

**Comment by chusiang** [comment]
coscup with Logbot.
- day1: http://logbot.g0v.tw/channel/coscup/2013-08-03
- day2: http://logbot.g0v.tw/channel/coscup/2013-08-03

by the way, 是否考慮把 Web IRC 整個嵌入 MOPCON 官方的網頁呢?
- [加入討論 | Ubuntu-TW](http://portal.ubuntu-tw.net/content/page/70634)
- [誰在聊天 | Ubuntu-TW](http://portal.ubuntu-tw.net/irclogs)
