### ISSUE TITLE
講者頁面 API

### ISSUE THREAD

**Issue by FWcloud916** [MOPCON/MOPCON#388]
#386

可以將 2019 年的講者 API 邏輯抽出來，在建立 2020 講者 API

設計稿：
https://app.zeplin.io/project/5ed9b2c3ffea64b7a95e91cc/dashboard

**Comment by FWcloud916** [comment]
請 @unciax  幫忙

**Comment by unciax** [comment]
有幾個問題想要確定一下：
1. 今年的 tag 是不是只有單一色彩? (設計稿上目前有兩種版本XD)
2. 不同年份的 json 檔會如何存放?

**Comment by FWcloud916** [comment]
1. 我去問問
2. /api/resource/assets/json/ 一樣改分 2019/2020 ， 圖片也是

麻煩先幫我分好了XD
還是有其他想法也可以討論

**Comment by unciax** [comment]
如果資料來源改為 `/api/resource/assets/json/2019/` 跟 `/api/resource/assets/json/2020/` 
這部分會需要動 Controller 取資料路徑的邏輯
由於大部分的 Controller 都是繼承這隻，修改後影響的層面滿廣的
這部分是不是應該要先把測試案例補齊全一點再修改會比較安心呢? 還是目前的時程沒有那麼充裕?

剛剛試著改一次之後發現測試幾乎全死光了XDD

**Comment by unciax** [comment]
所以路徑應該會變成 `/api/resource/assets/json/2019` 及 `/api/resource/assets/json/2020` ?

如果是這樣我想分幾段處理好了
1. 先改 json 的路徑，並調整 Controller 讓 2019 的 api 可以正常運作
2. 調整 images 的路徑及相關程式
3. 將講者共通的邏輯抽成共用

**Comment by FWcloud916** [comment]
> 所以路徑應該會變成 `/api/resource/assets/json/2019` 及 `/api/resource/assets/json/2020` ?

對

> 如果是這樣我想分幾段處理好了
> 
> 1. 先改 json 的路徑，並調整 Controller 讓 2019 的 api 可以正常運作
> 2. 調整 images 的路徑及相關程式
> 3. 將講者共通的邏輯抽成共用

好喔 麻煩你了!

**Comment by unciax** [comment]
目前的想法 Controller 可能可以改成這樣

- Controllers
    - Year2019
        - {2019 自己的 Controllers，裡面可能就放一個 year 變數且繼承 Base Function Controller}
    - { Base Function Controllers (AppHome, Session, Speaker...) }
    - ApiTrait.php
    - Controller.php
    - FacebookController.php

不知道 @FWcloud916 跟 @a8264347 這邊的想法是?

**Comment by hashman** [comment]
可以嘗試這樣進行，但記得 main goal 是不要調整到原本的 route 要確保舊的 client 在 access 這些 API 都是正常的，這個調整會比較辛苦一點，在麻煩 @unciax 幫忙， code review 的時候我也一起幫忙，謝謝

**Comment by a8264347** [comment]
拍謝 最近公司比較忙! 現在正在看!

**Comment by FWcloud916** [comment]
我覺得沒有問題

**Comment by unciax** [comment]
@hashman  想確定一下現在有哪些 client 會使用到這組 API?

另外有個想法是：
route 增加兩組 prefix `latest` 及 `2020` ，有點類似其他系統的 api 設計
這樣子官網可以直接用 `2020` (\api\2020\speaker)
APP (推測有用?) 可以直接用 `latest` (\api\latest\speaker)

不知道這樣可不可行?

**Comment by FWcloud916** [comment]
@unciax 目前會用的是 App 跟 官網
兩邊用的是一樣的 api 應該不用在分 `latest`

**Comment by hashman** [comment]
> @hashman 想確定一下現在有哪些 client 會使用到這組 API?
> 
> 另外有個想法是：
> route 增加兩組 prefix `latest` 及 `2020` ，有點類似其他系統的 api 設計
> 這樣子官網可以直接用 `2020` (\api\2020\speaker)
> APP (推測有用?) 可以直接用 `latest` (\api\latest\speaker)
> 
> 不知道這樣可不可行?

通常 API 的設計還是要保留原本網址的設計，像是 v1 v2 這樣的設計方式， 2019 這個目錄目前官網跟 App 都有在用 2019 的官網也會持續的抓取 2019 的 prefix route ，所以這個 route 是不會拿掉的，個人持跟方威一樣的想法

有問題可以再討論

**Comment by unciax** [comment]
hmm... 感覺兩位有點誤會我的意思

1. 2019 這個 prefix 沒有要拿掉，因為 2019 的官網仍會使用
2. 2020 跟 latest 指向的都是 2020 ，新增 latest 的用意在於 App 不用每年去改 api url (我看 iOS 版是直接寫死，Android 看起來是用環境變數)
3. 官網不用 latest 的原因在於 code 本身就是以年份分別去管理的

整體下來 Api Server 的 route 應該會像下面這樣

- /api
    - latest (for 官網，以系統年度顯示，同 2020)
    - 2020 (for App)
    - 2019

**Comment by a8264347** [comment]
嗨嗨 昨天看完卡司的code 跟 想法 剛好有去找 mutiple prefix 的議題

配合卡司的想法把今年App 走的 routes直接寫在 latest /2020 prefix 底下?

https://stackoverflow.com/questions/45809006/multiple-prefix-with-the-same-route-group/45809095

**Comment by hashman** [comment]
這種作法可能會有個問題，每年的 API Response 不一定會相同，所以等於說如果今天新的 API latest Response 改了結構，舊的 Client APP 沒有套用最新的程式，卻是抓取最新的 API Response 這樣可能就會照成問題，所以比較保險的做法還是需要將設定該 APP 可以套用的 API Response uri 來進行使用，這樣舊版的 Client 還是可以正常運作，然後新版的就依照新的規格下去跑，實務上公司也大多都會用這樣的方式來維護 API ，確保舊 APP 的可用性

當然我們也是可以考慮強更（強制更新），確保每個 APP 都一定是最新的，這樣就可以不用管舊 APP 了，這個也是一個作法，在 MOPCON 的使用情境開強更是可以接受的
