### ISSUE TITLE
Sharrre 的 G+ & Twitter 數字有問題

### ISSUE THREAD

**Issue by ericpi** [MOPCON/MOPCON#40]
G+ 已經 85, Twitter 已經 10, 但兩者都顯示 8,
要麻煩協助修正囉.

**Comment by CQD** [comment]
嗯...shareme 裡面的 URL 應該是 https://www.facebook.com/mopcon 還是 http://mopcon.org?

剛剛試了一下

https://www.facebook.com/mopcon 會是
8(G+) + 760(FB) + 8(Twitter) = 776

http://mopcon.org 會是
65(G+) + 70(FB) + 17(Twitter) = 152

**Comment by ericpi** [comment]
應該是 https://www.facebook.com/mopcon 
不過... 有辦法抓成 65(G+) + 760(FB) + 17(Twitter) 嗎? :p

**Comment by evan3rd** [comment]
應該是無法解決了, 這裡決定換成其他套件
