### ISSUE TITLE
講者介紹頁面

### ISSUE THREAD

**Issue by Mikimoto** [MOPCON/MOPCON#41]
第一位講者資料已經寄出給組長

**Comment by ericpi** [comment]
第二位講者資料也出來了, 能否先讓第一位講者資料上線?
我們希望每次上一位講者資料, 才有行銷操作空間.

**Comment by CQD** [comment]
加上講者介紹頁面了。雖然有點樸素...

**Comment by ksdgroup** [comment]
還有 Kdan、KKBOX(四位講者) 資料都已經到很久了, 
能跟議程追下資料嗎? 

本週新聞又斷炊了 ＠＠

**Comment by jserv** [comment]
Roger it.

**Comment by Mikimoto** [comment]
新的講者出爐，請更新

**Comment by ericpi** [comment]
剛剛寄出 KKBOX & Kdan 講者資料給 it, 也請 jserv  看下是否之前有收到這四位講者資料(8/26 e-mail).

**Comment by ericpi** [comment]
rogery 是有照片的, 我回信了

**Comment by Mikimoto** [comment]
建議一下，依據現有格式，每列三名，可以讓每一列都齊頭嗎？

如果有些講者簡介比較短，排版就顯得很凌亂

**Comment by pcedison** [comment]
感覺目前的講者頁面排版，每位講者的資訊也都格式不一，是否經由一些微調後，可讓講者格式盡可能相同，這樣後續微調版面上應可改善一些。

**Comment by Mikimoto** [comment]
全上結束這回合
