### ISSUE TITLE
講者頁面 Modal 顯示異常

### ISSUE THREAD

**Issue by Tzuhui** [MOPCON/MOPCON#425]
操作與狀況描述：
當複製講者連結，用 `/2020/speaker/18` 進入後
關閉 Modal 後，點選其他 speaker，Modal 資料都為 id 18 的那一位

再請 @jedy05097952 幫忙處理，感謝

**Comment by hiro05097952** [comment]
fixed:
https://github.com/MOPCON/MOPCON/pull/426
