### ISSUE TITLE
Social Plugin 中 Twitter 的泡泡視窗太短了

### ISSUE THREAD

**Issue by Mikimoto** [MOPCON/MOPCON#45]

**Comment by evan3rd** [comment]
這裡要注意 1024x768 screen 會有折行的情形

**Comment by CQD** [comment]
看起來是當初想把泡泡中的「followers」字樣擋掉，不過因為是硬算寬度所以數字不一樣的時候可能後面的「f」會跑出來。

這個稍微麻煩一點， twitter 自己沒提供把這串字藏起來的做法。

今天晚上應該可以解決...

**Comment by CQD** [comment]
一下拿不掉 followers 字樣，會踩到 same origin policy...

先讓 followers 能夠完整顯示出來，因為 twitter 區塊的長度變長所以調整一下版型把 twitter 放到最後面。
看起來比較不會那麼奇怪

**Comment by Mikimoto** [comment]
好像暫時也只有這個方法
