### ISSUE TITLE
英文版 Call for Paper 頁面

### ISSUE THREAD

**Issue by jserv** [MOPCON/MOPCON#47]
不確定是否有用，但有助於議程的工作，應該試試。

Translation for cfp.php:

Every session time slot at MOPCON is about 40 min (Q&A included), and here are the information entries for submitting speaking proposal:
- Name and/or nickname
- Contact information (email, cellphone number)
- Topic
- Abstract in 250 words
- Bio in 250 words

Please submit your speaking proposal before Sep 15, 2013, and the session committee will inform you about the availability of the session proposal before Sep 28, 2013.

It is the pleasure of MOPCON committee to invite you to submit session proposals for the following fields:
- Use case of mobile application operations
- Mobile application development
- Digital media and content oriented delivery

Additionally, we are willing to accept various interesting applications beyond the above topics, such as wearable technologies and HTML5 based cross-device applications.

**Comment by CQD** [comment]
會有英文版的演講徵求書 PDF 跟 Registrano 連結嗎？

**Comment by jserv** [comment]
英文 CfP PDF 待補，Registrano 內文會補上英文摘要

**Comment by CQD** [comment]
http://mopcon.org/2013/cfp_en.php
