### ISSUE TITLE
Banner 圖檔有點大，要等約十秒才下載完畢

### ISSUE THREAD

**Issue by cdchen** [MOPCON/MOPCON#5]
FYI

**Comment by Mikimoto** [comment]
Cd , 快點改

**Comment by cdchen** [comment]
Dear, 報告，遵命!!

Mikimoto notifications@github.com 於 2013/6/7 上午11:15 寫道：

> Cd , 快點改
> 
> —
> Reply to this email directly or view it on GitHub.

## 

陳 永昇 (Cd Chen)
http://www.cdchen.idv.tw/
mailto:cdchen@cdchen.idv.tw
mailto:cdchen.tw@gmail.com
mailto:cdchen@me.com
msn:cdchen@cdchen.idv.tw
icq:3345768

**Comment by cdchen** [comment]
報告是，馬上處理。

**Comment by cdchen** [comment]
fixed.
