### ISSUE TITLE
官網簡體、日文版

### ISSUE THREAD

**Issue by Mikimoto** [MOPCON/MOPCON#51]
看看明年是不是有機會往國際市場進軍 :p

**Comment by CQD** [comment]
這可能要花一些時間...現在的英文版是手動複製一份 code 出來跟原本的檔案放一起，簡體跟日文也這麼搞的話會很難維護[切腹]

要花一些時間整理一下 code 跟避免 link 死掉...

**Comment by Mikimoto** [comment]
明年規劃時討論
