### ISSUE TITLE
講者頁面排版亂掉了...

### ISSUE THREAD

**Issue by ericpi** [MOPCON/MOPCON#53]
Chrome 講者卡間空隙消失導致有些地方會重疊到... Firefox則上上半部有空隙, 下半部重疊...
http://mopcon.org/2013/speakers.php

**Comment by ericpi** [comment]
Firefox:
![firefox](https://f.cloud.github.com/assets/80681/1070804/0d92fd9a-1465-11e3-9cd1-e96a312ddbdb.png)

Chrome:
![chrome](https://f.cloud.github.com/assets/80681/1070805/15237814-1465-11e3-9c18-8bc6f89423a6.png)

**Comment by CQD** [comment]
Resize 視窗會正常，Firefox 重新整理也會正常....

masonry 觸發時間點的問題？晚點來看看....

**Comment by CQD** [comment]
果然，本機測不出來...回家丟到哪台機器上試看看。

**Comment by CQD** [comment]
root cause 不確定，先用畫面載入後 0.3 秒重新計算物件高度的方式來避開...

**Comment by ericpi** [comment]
看起來好像好了

**Comment by CQD** [comment]
這個應該可以先關了...
