### ISSUE TITLE
於「聯絡方式」加入 WebIRC?

### ISSUE THREAD

**Issue by chusiang** [MOPCON/MOPCON#59]
建議於「聯絡方式」頁面嵌入 WebIRC 的 iframe。
- [Site of Demo](http://portal.ubuntu-tw.net/content/page/70634)
- [Source code of Demo](https://github.com/chusiang/ubuntu-tw-website/blob/master/ircweb.html)

**Comment by chusiang** [comment]
iframe

```
<iframe src="http://webchat.freenode.net?channels=%23mopcon&uio=d4" width="647" height="400"></iframe>
```

**Comment by Mikimoto** [comment]
直接新增 IRC Web Link 取代
