### ISSUE TITLE
請把目前議程簡表改版

### ISSUE THREAD

**Issue by Mikimoto** [MOPCON/MOPCON#63]
可以參考去年議程表

把成講者簡介、講題簡介、跟未來的 slide , 錄影可以結合的形式

**Comment by xup62j4** [comment]
請問 "講者簡介、講題簡介" 要參考哪份文件？

**Comment by Mikimoto** [comment]
請參考 google doc 裡面 MOPCON/2013/議程表，統一在這裡維護

**Comment by xup62j4** [comment]
已修改第一日的議程表
內容還得請議程組協助

**Comment by ezoengine** [comment]
好的，今日我就會校閱內容，謝謝

Marty
2013/10/4 上午3:09 於 "JohnDoe" notifications@github.com 寫道：

**Comment by evan3rd** [comment]
這個修改應該開 feature
直接放到 develop 後，造成其他緊急修改 deploy 的困難

**Comment by Mikimoto** [comment]
已經切 branch，新議程表請在 feature/newSessionTable 上發展

**Comment by xup62j4** [comment]
好的，瞭解！

**Comment by Mikimoto** [comment]
目前進度如何？ 時間有點急迫了

**Comment by xup62j4** [comment]
已經在 feature/newSessionTable 上更新過新版的議程表
有請議程組看是否有問題需要做修改

**Comment by Mikimoto** [comment]
已經先簡單改一個版本上 feature/SessionTable

**Comment by ezoengine** [comment]
Hi,Mikimoto

回報問題,議程json資料還是沒更新

Marty
2013/10/18 下午7:19 於 "Mikimoto" notifications@github.com 寫道：

**Comment by Mikimoto** [comment]
我先處理一部分了，先上架，確定 JSON 可以匯得出來
嶧城資料更新，請 Marty / Marcus 再巡一次吧
