### ISSUE TITLE
2012 首頁會連結至 2013

### ISSUE THREAD

**Issue by chusiang** [MOPCON/MOPCON#65]
在官網上方的選項中點擊 MOPCON 2012 會進入舊版的網站 (http://mopcon.org/2012/activity.php) ，這時就會發現 MOPCON 2012 Logo 的連結是連到 2013，不知這算不算是個 BUG?

**Comment by CQD** [comment]
等下來改一下，2012/2013 的 logo 都是連到 http://mopcon.org

應該改成連到當年度首頁(例如 http://mopcon.org/2013/ )，然後在什麼地方加一個 http://mopcon.org

**Comment by CQD** [comment]
fixed
