### ISSUE TITLE
把 2013 的議程影片放上網站

### ISSUE THREAD

**Issue by CQD** [MOPCON/MOPCON#68]
就....把 2013 的議程影片放上網站...

**Comment by CQD** [comment]
有幾個影片在 [youtube 頻道](http://www.youtube.com/user/mopcon2012)上沒看到，正常乎？
- 第一天
  - 半路
- 第二天
  - PTT
  - TonyQ
  - Evan Wu

**Comment by jserv** [comment]
半路的議程謝絕錄音錄影，議程組提供文字紀錄

**Comment by CQD** [comment]
- PTT
- TonyQ
- Evan Wu

都上去了，感謝 eric 葛格
