### ISSUE TITLE
2012 年花絮的 irc log 出現亂碼

### ISSUE THREAD

**Issue by Mikimoto** [MOPCON/MOPCON#7]

**Comment by Mikimoto** [comment]
需要將目前的文字檔整理為 html 格式

**Comment by ericpi** [comment]
可以直接用 github 連結吧?
https://raw.github.com/chusiang/irc_log/master/mopcon/irc-mopcon-2012.log

**Comment by Mikimoto** [comment]
因為連結阿翔那邊的網站，他又常改版，Link 已經失效多次，我想說自己存一份吧

**Comment by ericpi** [comment]
應該不用改 html 格式, 強制用控制 content type 跟編碼就可以了.
header('Content-type: text/plain; charset=utf-8');
echo file_get_contents('OOXX.log);

**Comment by cdchen** [comment]
這個 issue 還存在嗎?? 如果已經修復掉，麻煩兩位大大把這個 issue close 吧，謝啦!!

**Comment by xup62j4** [comment]
請問 http://test.mopcon.org/2012/day1.php 這隻程式放在哪個 branch 底下 ?

**Comment by Mikimoto** [comment]
抱歉，在我 local 端，還沒修正好就先不上傳，等一下再上傳

**Comment by Mikimoto** [comment]
暫時修正完畢，雖然我還是嫌太醜
