### ISSUE TITLE
2014 首頁 title 出現亂碼

### ISSUE THREAD

**Issue by xup62j4** [MOPCON/MOPCON#71]
http://imgur.com/3Vef9Ob

如果瀏覽器以 Big5 編碼開啟 , 會出現亂碼

**Comment by CQD** [comment]
這個是 utf-8，不應該讓瀏覽器用 big5 開 O_o

看了一下，meta 裡面沒設 charset，大概是這樣所以 opera 猜錯編碼了，來改。

**Comment by CQD** [comment]
如果沒其他類似問題就先關了...
