### ISSUE TITLE
bug report & suggestion

### ISSUE THREAD

**Issue by ericpi** [MOPCON/MOPCON#8]
all
1. FB 粉絲群不見了
2. 說好的 G+ "+1" 呢?
3. 其他->MOPCON 2012, 建議直接轉到花絮

index.php
1. 首頁三張照片圖檔太大
2. iPad mini Chrome版面沒問題, Android Browser/Chrome版面整個爛掉, 而且上方選單消失
3. 電腦上 browser 只要寬度小於 960px, 上方選單消失
4. 橫幅logo圖檔太大, 這種情況應該要考慮切圖排版, 而且這個設計其實不適合網站, 還不如之前測試那個藍底加 "I code, I spread I connect" 字樣適合各種設備看

social.php
1. CHK logo size 需要最佳化一下

2012/activity.php
1. 照片至少給個 G+ 那邊相簿網址: https://plus.google.com/b/116768206884057057248/photos/116768206884057057248/albums/5857404089929553185
2. 工作人員的話我記得也給了吧, 至少上個四位總召的話之類的

**Comment by Mikimoto** [comment]
拆散工作項目
