### ISSUE TITLE
聊天室

### ISSUE THREAD

**Issue by CQD** [MOPCON/MOPCON#81]
## 需求
- 不需要登入
- 可以設定名稱
- 網頁上可以用
## 可能做法
1. 沿用 IRC
   - 網頁上不好整合
   - so geek...有好有壞
2. 找其他的 Chat Service
3. 自己刻 Chat Room
   - WebSocket Chatroom?

**Comment by CQD** [comment]
http://socketo.me/

用 [React PHP](http://reactphp.org/) 刻的 WebSocket Library...或許可以在 AWS 上這樣跑。

**Comment by CQD** [comment]
http://caniuse.com/#search=websocket

Android < 4.4 全滅...Android 的 Chrome 要測看看

**Comment by sTinGe** [comment]
要不然就不要在 Android 上開聊天室?
(暗爽中...

**Comment by CQD** [comment]
實驗了一下，在我的筆電上面可以撐 26x 個 connection，資源吃不兇，大概是踩到了什麼系統的 connection 限制。

不過多做幾次 CPU 使用量就飛起來了，大概有 leaking，真的用的話可能要一天重開一次之類的...

另，我的 OneX+ 開 Chrome 跟內建 browser 都會動，4.2.2...

**Comment by CQD** [comment]
https://github.com/MOPCON/chat-php

成果先放在這邊，要找時間做壓測跟完善 client，現在 client 還沒有界面可以用，得開 dev console 控制。

然後 Android Chrome 開了聊天室以後就算螢幕關掉也能收到訊息...有點意外。

**Comment by chusiang** [comment]
不知可否直接使用 g0v 的系統? :P 
- [如何使用 IRC · g0v/dev Wiki](https://github.com/g0v/dev/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8-IRC)

**Comment by CQD** [comment]
是說看來是沒空弄完這東西...
