### ISSUE TITLE
組長會議 #9 的 issues list

### ISSUE THREAD

**Issue by ericpi** [MOPCON/MOPCON#84]
1)『MOPCON』的字體太小+沒有放在畫面中央+與背景色相比，顏色對比度低 (顏色過暗問題?)。======> mobile 版本時, 以圖內Mopcon為中心切圖。圖的對比調一下。
2) 放上前兩年的官網連結
3) 可以多加一個「活動簡介」嗎？ ===> ericpi 我寫我寫...
4) 可以加上簡中版跟英文版嗎？ ===> 能先用 google translate?
5) 網站的交通資訊 捷運部分 個人認為"至捷運美麗島站換乘橘線往西"中的"往西"改成"往西子灣方向"
6) Mobile 版本選單按鈕要不要加上 "選單" 字樣
8) Mobile 版本舉辦時間/slogan字體太小問題 ===> 同 1. 處理方式
9) 臉書 Link 沒有顯示圖示，只顯示說明，這樣算正常嗎？
10) 贊助商Logo圖片尺寸?  512 x 512
11) twitter 跟 G+ 圖示/連結: 
http://twitter.com/mopcon
http://google.com/+MopconOrg
12) 首頁 Facebook onMouseOver 不會有動畫效果?

討論資料請參考: https://docs.google.com/document/d/1gBHySFQEulUxmHMnyb19RXXRThCeDZ85PutzVNCAIqo/edit

**Comment by ericpi** [comment]
想確認一下官網 3) 大概要多少字? 或說最多可以塞多少字?

**Comment by ericpi** [comment]
說好的週日 update 狀況如何呢?

**Comment by CQD** [comment]
- 1,5,8,9,11,12 done
- 2 先放上歷年活動頁面的連結，歷年活動頁面調成跟 2014 同樣的 style，多層選單以 2014 的版型不太好搞..
- 4 google translate 的 code 不知道為什麼選單一直出不來，得從程式來處理。進行中
- 10 高度 192 px 以上，考慮到 retina 的話大一點好
- 6

**Comment by gonsakon** [comment]
1)   已換mobile banner
3)   活動簡介字數就差不多和2013首頁即可
10) 贊助商Logo圖片尺寸至少 請廠商提供512 x 512以上
