### ISSUE TITLE
組長會議 #16 的 issues list

### ISSUE THREAD

**Issue by WanJen** [MOPCON/MOPCON#85]
(1) 首頁：PC版與Mobile版的圖片，顯示調整為不同。
PC版首頁圖
![banner](https://cloud.githubusercontent.com/assets/3149036/3811365/8e9263d0-1c9e-11e4-84dd-7bfd5f46c86d.png)
Mobile版首頁圖
![index-banner-retina](https://cloud.githubusercontent.com/assets/3149036/3811380/aac8d660-1c9e-11e4-95ed-d2b73fb83ed1.png)
目前待修正的首頁
![screenshot_2014-08-04-22-03-16](https://cloud.githubusercontent.com/assets/3149036/3811386/c58907cc-1c9e-11e4-8f8d-6eca76dadd86.png)

(2) 社群：
A). MOSUT：更新社群LOGO，新增FB連結。
JPG檔
https://www.dropbox.com/s/l20ivzbzo3v8veg/MOSUT_LOGO-01.jpg
SVG檔
https://www.dropbox.com/s/tf8oijkcwq2dbpe/MOSUT_LOGO.svg
FB連結
https://www.facebook.com/groups/mosut/
B). CHK：Mobile破版。
![screenshot_2014-08-04-22-04-48](https://cloud.githubusercontent.com/assets/3149036/3811405/fb7c123e-1c9e-11e4-8e85-a3575a083413.png)
C). 新增社群：高雄前端、AKDG、Mobile Girls。

(3) 公告：內文裡的"連結"，文字會跑到背景以外。
![news](https://cloud.githubusercontent.com/assets/3149036/3811416/257e93f4-1c9f-11e4-8d30-dc7e9ed90bcd.jpg)

**Comment by ericpi** [comment]
其實可以貼圖, 你要不要把 e-mail 的圖貼上來

**Comment by CQD** [comment]
(1) 是前天更新 style 的時候有問題，先修正了
(4) 我現在一下沒辦法重現這狀況，大概跟(1)有關

(2) 是因為不同等級的贊助商的樣式不一樣。現在上線的贊助商不夠，看起來會怪怪的。

(3) 這個再來處理...

**Comment by gonsakon** [comment]
(2) B 與(3)已修正，
(2)A與(2)C 等我拿到android社團簡介資料會再一次做上去

**Comment by CQD** [comment]
這邊的都完成了
