### ISSUE TITLE
官網群募頁面

### ISSUE THREAD

**Issue by ericpi** [MOPCON/MOPCON#88]
可以許願有跟一樣的主文字+圖片內容, 以及轉址過去連結嗎?
https://www.flyingv.cc/project/2843

**Comment by ericpi** [comment]
或者是哪邊可以塞 "支持我們" 的顯眼連結

**Comment by gonsakon** [comment]
想到兩個方案，看是都做或者擇一

1.選單再多一個外連連結，叫做「群募」，另開連結連到flyingv
2.支持我們也可以放在「贊助」頁上面，開頭文案可改為：

「強力徵求贊助廠商，請快與我們（ sponsor [at] mopcon.org ）聯繫，
也極力歡迎各位到mopcon的flyingv群募頁面支持我們！」

**Comment by ericpi** [comment]
兩個都很優啊, 可以都做嗎?
而且同類型問題, 可能馬上也會用到 KKTIX 報名/個人贊助票的官網顯示

**Comment by ericpi** [comment]
現在看起來可以先不用了
