### ISSUE TITLE
新版官網文案調整

### ISSUE THREAD

**Issue by ericpi** [MOPCON/MOPCON#89]
- 第一段 "方向" 內文請協助更換為
  - 今年議程除了涵蓋以往 App開發、雲端服務、數位內容、創新營運四大主軸外，WWDC、Google I/O 兩大年度盛事聚焦的海量資料、穿戴式裝置、運動健康照護、家庭自動化、TV / 高畫質內容、簡化設計和開發流程等議題也都是重要行動應用的脈絡，豪華的講師陣容是 MOPCON 重要傳統，敬請期待完整議程公布！
- 最後一段 "報名資訊" 請協助更換為
  - 2013/10/26-27（六日兩天） => 2014/10/25-26（六日兩天）
  - 地點：高雄國際會議中心（ICCK）
  - 主題：App開發、雲端服務、數位內容、創新營運、海量資料、穿戴式裝置、運動健康照護、家庭自動化、TV / 高畫質內容、簡化設計和開發流程等最新行動應用趨勢 & 最夯的行動科技議題盡在 MOPCON，請密切注意[粉絲群](http://fb.me/mopcon)及官網的報名資訊！

以下要麻煩修改文字:
- 定調 “本年度” 精神意涵為 "I code, I spread, I connect”。 ==> 
  - 定調本年會精神意涵為 "I code, I spread, I connect"。
- 同時 App便利屋、APPGuru、Punapp等媒體報導給予本屆活動正面評價，亦獲得聯合報、經濟日報、自立晚報、聯合新聞網主流媒體報導 ==> 
  - 要麻煩把那些媒體連結 (http://mopcon.org/2013/) 也帶過來
- 徵稿連結 ==> 
  - 目前開放講者投稿

**Comment by gonsakon** [comment]
done
http://mopcon.org/2014_test/
