### ISSUE TITLE
請協助增加 KKTIX logo 到 "特別贊助"

### ISSUE THREAD

**Issue by ericpi** [MOPCON/MOPCON#91]
請使用這張圖片, 並連結到 https://kktix.com
https://www.dropbox.com/s/1b7on4rm6manxr6/kktix.png?dl=0

=== 文案如下 ===
KKTIX 是線上音樂領導品牌 KKBOX 旗下的全功能售票購票平台。無論找活動、辦免費活動、辦售票活動、研討會、演唱會、大食團、郊遊踏青... KKTIX 線上售票平台都是您的好去處。KKTIX 提供最順暢的購票體驗、最方便的售票平台，以豐富活動點綴眾人生活。

**Comment by gonsakon** [comment]
done
