### ISSUE TITLE
官網議程與講者更新 - AWS

### ISSUE THREAD

**Issue by WanJen** [MOPCON/MOPCON#93]
贊助商AWS的講者更新，資料如下，

(1) 10/25 10:40~11:20 三廳

A. 講者簡介

James Tien has been responsible for business development activities in Taiwan for the past 2.5 years since he joined AWS in May 2012. He helps enterprises of all sizes, SMBs and startups to leverage the benefits of the AWS cloud to accelerate their businesses. He enjoys seeing innovations enabled by the cloud. He enjoys seeing Taiwanese companies scale and compete globally.
James Tien has a degree in Electrical Engineering from University of Victoria, Canada. Now calling Singapore home, he has spent much of his time living in different places such as Australia, Canada, and the USA. He has a lot of passion for technologies and music. Spotify is one of his favorite apps to date.

B. 講者名稱
James Tien

C. 講者頭銜
Business Development Manager, AWS

D.講者照片
![james tien](https://cloud.githubusercontent.com/assets/3149036/4571483/f8eee6b6-4f77-11e4-8b97-92b77bfaded6.jpg)

E. 議程分類
請把分類標籤「技術」改為「營運」

F. 議程標題
Building Mobile Apps on AWS

G. 議程簡介
AWS makes development of cross-platform mobile applications easy. With highly-scalable cloud services, mobile developers can build powerful cloud-backed mobile apps with just a few lines of code. In this session, you will learn how to connect directly to these services and how to build a powerful back end for your Android and iOS applications. We will also share some best practices from other successful apps such as Flipboard and Supercell so you can focus on differentiating your app functionality whilst leaving the 'table stakes' with no differentiated value to the cloud.

(2) 10/26 14:20~15:00 三廳

A. 講者簡介

Ken在IT界擁有+15年的資深經驗，曾經在Red Hat擔任大中華地區的方案架構經理並領導著頂尖科技團隊與政府合作開發各樣FSI，Telco相關的解決方案，協助銷售團隊去穩定和提升商機。
Ken在2011年加入AWS，推廣AWS雲端服務並提供AWS技術專業指導，幫助用戶快速上手。

B. 講者名稱
Ken Chan

C. 講者頭銜
AWS Solution Architect, Asia Pacific

D.講者照片
![ken](https://cloud.githubusercontent.com/assets/3149036/4571487/0aa2e18c-4f78-11e4-9653-d9bf75e42671.jpg)

E. 議程標題
Developing Mobile apps with AWS

F. 議程簡介
Learn about AWS' latest portfolio of mobile optimized services. Whether you are a mobile developer topping the charts in the app store, or a business trying to be "Mobile-first", the cloud is a critical part of your solution, enabling you to build fast and scale easily. This session will help you understand how to leverage the full power of the AWS Cloud Platform offering in your mobile apps.

Do you aspire to quickly build a mobile app or game and deliver engaging experiences to millions of users? Learn how to get started with AWS Mobile Services. This session will introduce the essential building blocks of a cloud-backed mobile app. The session will provide an overview of AWS Mobile Services and Connectors included in the AWS Mobile SDK and demonstrate how you can leverage these to deliver engaging experiences in your app.

**Comment by ericpi** [comment]
已經上線
