### ISSUE TITLE
官網議程與講者更新 - GitCafe

### ISSUE THREAD

**Issue by WanJen** [MOPCON/MOPCON#94]
贊助商GitCafe的議程與講者更新，資料如下，

(1) 10/25 上午(確切時間未定) Open Lab

A. 講者簡介

一個相信開放/ 自由/ 共享/ 創新可以讓人類變的更好的人類。以 Open Source Evangelist 為志業，參與並投入開源及技術社群活動的組織運營。從 2009 年起在中央研究院的自由軟體鑄造場研究開源授權、商業模式及社群經營，2013 年出任 JavaScript Developers Conference (JSDC) 2013 總召集人，並與 Ant Tzeng 共同創辦 BELP 社群。2014 年 2 月赴中國，加入上海東革志信息科技有限公司 GitCafe.com，擔任市場總監，並投入 Shanghai Linux User Group 的組織協調工作。對於中國及台灣的互聯網產業及技術社群運營又有更進一步的了解及心得。

B. 講者名稱
Richard Lin 林旅強 (Legist 強)

C. 講者頭銜
GitCafe 市場總監

D. 講者照片
![richard lin for mopcon 2014 800_600](https://cloud.githubusercontent.com/assets/3149036/4572865/7b496fec-4f8b-11e4-87dd-05da2f533713.jpg)

E. 議程標題
社群與企業共創開源生態系統--兩岸技術社群運營經驗談

F. 議程簡介
社群經營與商業運作看似不易兼容，技術人對商業有時不感興趣，甚至沒有好感。若要打造一個好的開源社群的生態系統，在社群堅守技術分享、企業力求商業價值之中，要達到雙贏成果需進行各項嘗試。強哥將分享在台灣和中國社群經營的經驗及觀察，讓社群組織者、企業或開發者個人，都能在共建良好生態系統的過程中找到最佳位置。

**Comment by CQD** [comment]
講者資料加上[強哥](http://mopcon.org/2014/speakers.php#legist)了，不過議程資料等時間確定在來加。
