### ISSUE TITLE
官網議程更新

### ISSUE THREAD

**Issue by WanJen** [MOPCON/MOPCON#95]
官網議程頁資料更新

(1) 10/25 08:45~09:00

A. 標題「ASUSCloud 贊助抽獎活動」中，「ASUSCloud」中間加入空格分開為「ASUS Cloud 贊助抽獎活動」。

B. ASUS Cloud的Logo換成彩色版圖片。

Logo資料夾：
https://drive.google.com/?usp=folder&authuser=0#folders/0B6DEnjQGak61QjFncFVFRVkzbTA

(2) 10/25 09:00~09:40

A. 講者照片換成講者本人，顯示範圍與手冊一致。

照片圖檔：
https://docs.google.com/file/d/0B3Sj2gsEx2VTVW01eU15Q2QwTmw5WkZPdVFUdElvVmJGZmtZ/edit

手冊圖檔：
https://www.dropbox.com/s/bu1s57kcx6q38wg/2014%E6%89%8B%E5%86%8A_final.png?dl=0

B. 議題介紹內文第一個字「lIntroducing」，改為「Introducing」。

(3) 10/25 09:40~09:50

A. 圖片改成MOPCON Logo，跟網頁Header用的MOPCON Logo一樣。

B. 「神秘嘉賓」改為「休息一下」。

C. 把講者簡介的「猜猜我是誰」改成「跟隔壁的會眾交換名片，自我介紹你是誰」。

(4) 10/25 09:50~10:30 一廳

A. 「Drake (官順暉)」改為「官順暉 (Drake)」。(與手冊一致)

(5) 10/25 09:50~10:30 二廳

A. 「上官林傑 (ericsk)」改為「上官林傑 (Ericsk)」。

B. 講者簡介的最後一句「講題標語: 快速、可靠、穩定的應用程式」刪除。

(...繼續增加中 by 婉貞)

**Comment by CQD** [comment]
休息時間改成顯示一條棒棒

照片/logo 也改了。不過現在變成有的議程會連結到講者有的會連結到贊助商，要麻煩幫忙確認一下是不是資料都正常

**Comment by chusiang** [comment]
看來 Asus Cloud 的資料有誤。
- https://github.com/MOPCON/MOPCON/issues/96
